---
dependencies: [ ]

galaxy_info:
  author: Jeroen Geusebroek
  description: Install ands configures Docker Engine on Redhat/CentOS and Debian/Ubuntu
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
      - all
    - name: Debian
      versions:
      - jessie
      - wheezy
    - name: Ubuntu
      versions:
        - trusty
        - xenial
  categories:
    - system
