---

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present

- name: install basic packages
  yum:
    name:
      - git
      - curl
      - zip
      - wget
      - vim
    state: present